
spring:
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.35.152:3306/peiwan?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
<<<<<<< HEAD
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.peiwan.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
=======
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.peiwan.bean
>>>>>>> 9fb37ab764f9d72d5831f5bcbec6d7e6ae795c6e


